### ISSUE TITLE
Great stuff

### ISSUE THREAD

**Issue by bodiam** [SuperMMX/asciidog#8]
Hi Xuan,

This is pretty cool stuff. I saw you live in Sydney too, maybe you have some time to catch up?

Send me a tweet or msg: erik.pragt@gmail.com!

Cheers,

Erik

**Comment by SuperMMX** [comment]
@bodiam Sorry for this very late response, Erik, time goes really fast, this has been almost two years already !!

We can definitely meet sometime, I just saw the Sydney Kotlin Meetup happened on April 19th, maybe I can attend the next one to catch up with you.

**Comment by SuperMMX** [comment]
I picked up this project again recently, because I have my documents in AsciiDoc, I need to make this work for my own requirements.  Although AsciiDoctor works well, but I can't really help or do my own stuff with Ruby, hopefully this little project can grown big to also help others.

**Comment by bodiam** [comment]
Hi Xuan,

No worries! The meetup actually got moved to a new date, so hopefully we can catchup soon!

Cheers,

Erik
